Repository August-ToyProject/PDF-Quiz, pull requests merged in 2024-08, with the labels that each got.

#13 feat[#10] : Fastapi 기본설정 및 라우트 확인 완료
  .gitignore
  BE/fastapi/quiz-application/.gitignore
  BE/fastapi/quiz-application/README.md
  BE/fastapi/quiz-application/requirements.txt
  BE/fastapi/quiz-application/src/__init__.py
  BE/fastapi/quiz-application/src/app/__init__.py
  BE/fastapi/quiz-application/src/app/api/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/docs/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/endpoints/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/endpoints/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/helpers/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/repository/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/service/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/shema/__init__.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/__init__.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/docs/__init__.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/endpoints/__init__.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/endpoints/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/__init__.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/repository/__init__.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/__init__.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/shema/__init__.py
  BE/fastapi/quiz-application/src/app/app.py
  BE/fastapi/quiz-application/src/app/urls.py
  BE/fastapi/quiz-application/src/common/__init__.py
  BE/fastapi/quiz-application/src/common/conf/__init__.py
  BE/fastapi/quiz-application/src/common/conf/settings.py
  BE/fastapi/quiz-application/src/packages/_init__.py
  BE/fastapi/quiz-application/src/packages/decorators/__init__.py
  BE/fastapi/quiz-application/src/packages/decorators/logging_decorator.py
  BE/fastapi/quiz-application/src/packages/decorators/processing_time.py
Labels: 기능 개발

#14 feat[#10] : springboot 초기설정
  BE/spring/quiz-application/.gitignore
  BE/spring/quiz-application/build.gradle
  BE/spring/quiz-application/gradle/wrapper/gradle-wrapper.jar
  BE/spring/quiz-application/gradle/wrapper/gradle-wrapper.properties
  BE/spring/quiz-application/gradlew
  BE/spring/quiz-application/gradlew.bat
  BE/spring/quiz-application/settings.gradle
  BE/spring/quiz-application/src/main/java/com/quizapplication/QuizApplication.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/redis/RedisConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/redis/RedisService.java
  BE/spring/quiz-application/src/test/java/com/quizapplication/QuizApplicationTests.java
  BE/spring/quiz-application/src/test/java/com/quizapplication/config/RedisCrudTest.java
Labels: 기능 개발

#18 feat[#12]: 프로젝트 초기 환경 세팅
  FE/login/.eslintrc.cjs
  FE/login/.gitignore
  FE/login/README.md
  FE/login/index.html
  FE/login/package-lock.json
  FE/login/package.json
  FE/login/public/vite.svg
  FE/login/src/App.css
  FE/login/src/App.tsx
  FE/login/src/assets/react.svg
  FE/login/src/index.css
  FE/login/src/main.tsx
  FE/login/src/vite-env.d.ts
  FE/login/tailwind.config.js
  FE/login/tsconfig.app.json
  FE/login/tsconfig.json
  FE/login/tsconfig.node.json
  FE/login/vite.config.ts
Labels: 기능 개발

#20 feat[#9]: 회원가입 페이지 추가
  FE/login/src/App.tsx
  FE/login/src/assets/react.svg
  FE/pdf_quiz/.eslintrc.cjs
  FE/pdf_quiz/.gitignore
  FE/pdf_quiz/README.md
  FE/pdf_quiz/index.html
  FE/pdf_quiz/package-lock.json
  FE/pdf_quiz/package.json
  FE/pdf_quiz/postcss.config.js
  FE/pdf_quiz/public/vite.svg
  FE/pdf_quiz/src/App.css
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/index.css
  FE/pdf_quiz/src/main.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
  FE/pdf_quiz/src/vite-env.d.ts
  FE/pdf_quiz/tailwind.config.js
  FE/pdf_quiz/tsconfig.app.json
  FE/pdf_quiz/tsconfig.json
  FE/pdf_quiz/tsconfig.node.json
  FE/pdf_quiz/vite.config.ts
Labels: 기능 개발

#17 feat[#15]: 기본적인 회원 가입
  BE/spring/quiz-application/build.gradle
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/swagger/SwaggerConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/MemberResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/MemberRepository.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberServiceImpl.java
Labels: 기능 개발

#23 Feature/#19 fe 로그인
  FE/pdf_quiz/package-lock.json
  FE/pdf_quiz/package.json
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
Labels: 기능 개발

#24 feat[#22]: 회원가입 검증 기능
  BE/spring/quiz-application/build.gradle
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/BusinessException.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/BusinessExceptionResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ErrorCode.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ExceptionHandlerController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/DuplicateEmailException.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/MemberRepository.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberServiceImpl.java
Labels: 기능 개발

#27 feat[#25] : Fast API 퀴즈 생성 프롬프트 추가 및 테스트 완료
  BE/fastapi/quiz-application/requirements.txt
  BE/fastapi/quiz-application/src/app/api/file_service/endpoints/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/helpers/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/service/file_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/endpoints/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/shema/quiz_request.py
  BE/fastapi/quiz-application/src/common/conf/settings.py
Labels: 기능 개발

#31 feat[#30]: 로그인 기능
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomAuthenticationFilter.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomUserDetailsService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/handler/LoginFailureHandler.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/handler/LoginSuccessHandler.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Role.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/LoginRequestDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/MemberRepository.java
Labels: 기능 개발

#34 feat[#26]: 마이페이지 레이아웃 구성 및 공용 모달 구현
  FE/pdf_quiz/.vite/deps_temp_abeeb767/package.json
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/components/Modal.tsx
  FE/pdf_quiz/src/components/Upload.tsx
  FE/pdf_quiz/src/components/test.txt
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
Labels: 기능 개발

#36 refactor[#33] : 불필요 로직 및 코드 리팩토링
  BE/fastapi/quiz-application/faiss_indexes/20195298_박준용_UROP_최종결과보고서_20240808_013030/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/20195298_박준용_UROP_최종결과보고서_20240808_013030/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/4. 프록시 패턴과 데코레이터 패턴_20240808_231627/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/4. 프록시 패턴과 데코레이터 패턴_20240808_231627/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/5. 동적 프록시 기술_20240808_232629/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/5. 동적 프록시 기술_20240808_232629/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (2)_20240808_232553/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (2)_20240808_232553/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (5)_20240808_232929/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (5)_20240808_232929/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (5)_20240808_234434/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (5)_20240808_234434/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/네카라쿠배+개발자가+알려주는+개발자+서류+전형의+모든+것_수정판.pdf-20231008021505_20240808_012835/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/네카라쿠배+개발자가+알려주는+개발자+서류+전형의+모든+것_수정판.pdf-20231008021505_20240808_012835/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/실습코드A+세종대학교 알고리즘 실습문제 정답_20240808_223606/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/실습코드A+세종대학교 알고리즘 실습문제 정답_20240808_223606/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/웹서버컴퓨팅_2023 기말실기 문제지_20240808_011459/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/웹서버컴퓨팅_2023 기말실기 문제지_20240808_011459/index.pkl
  BE/fastapi/quiz-application/src/app/api/file_service/docs/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/endpoints/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/endpoints/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/helpers/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/repository/__init__.py
  BE/fastapi/quiz-application/src/app/api/file_service/shema/__init__.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/docs/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/endpoints/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
  BE/fastapi/quiz-application/src/app/app.py
Labels: 리팩토링

#39 feat[#38]: JWT 토큰
  BE/spring/quiz-application/build.gradle
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/QuizApplication.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/TokenDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/TokenProvider.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomAuthenticationFilter.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityUtil.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberServiceImpl.java
Labels: 기능 개발

#43 Feature/#35 fe 업로드구현
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/assets/X.png
  FE/pdf_quiz/src/assets/folder.png
  FE/pdf_quiz/src/assets/pdf_logo.png
  FE/pdf_quiz/src/assets/search.png
  FE/pdf_quiz/src/components/Modal.tsx
  FE/pdf_quiz/src/components/Upload.tsx
  FE/pdf_quiz/src/components/test.txt
  FE/pdf_quiz/src/pages/MyPage.tsx
Labels: 기능 개발

#48 feat[#45]: OMR UI 렌더링 구현
  FE/pdf_quiz/src/Hooks/OMR.tsx
Labels: 기능 개발

#54 Feature/#32 be fast api 랭그래프
  BE/fastapi/quiz-application/faiss_indexes/20195298_박준용_UROP_최종결과보고서_20240808_013030/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/20195298_박준용_UROP_최종결과보고서_20240808_013030/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/4. 프록시 패턴과 데코레이터 패턴_20240808_231627/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/4. 프록시 패턴과 데코레이터 패턴_20240808_231627/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/5. 동적 프록시 기술_20240808_232629/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/5. 동적 프록시 기술_20240808_232629/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (2)_20240808_232553/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (2)_20240808_232553/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (5)_20240808_232929/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (5)_20240808_232929/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (5)_20240808_234434/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/TA-NGCF_제출용 (5)_20240808_234434/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/네카라쿠배+개발자가+알려주는+개발자+서류+전형의+모든+것_수정판.pdf-20231008021505_20240808_012835/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/네카라쿠배+개발자가+알려주는+개발자+서류+전형의+모든+것_수정판.pdf-20231008021505_20240808_012835/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/실습코드A+세종대학교 알고리즘 실습문제 정답_20240808_223606/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/실습코드A+세종대학교 알고리즘 실습문제 정답_20240808_223606/index.pkl
  BE/fastapi/quiz-application/faiss_indexes/웹서버컴퓨팅_2023 기말실기 문제지_20240808_011459/index.faiss
  BE/fastapi/quiz-application/faiss_indexes/웹서버컴퓨팅_2023 기말실기 문제지_20240808_011459/index.pkl
  BE/fastapi/quiz-application/requirements.txt
  BE/fastapi/quiz-application/src/app/api/file_service/endpoints/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/helpers/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/service/file_service.py
  BE/fastapi/quiz-application/src/app/app.py
Labels: 기능 개발

#57 refactor[#53]:프롬프트 재적용
  BE/fastapi/quiz-application/src/app/api/file_service/endpoints/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/helpers/file_service.py
  BE/fastapi/quiz-application/src/app/api/file_service/service/file_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/endpoints/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/shema/quiz_request.py
Labels: 리팩토링

#58 feat[#47]: python-kafka 적용 및 테스트 완료
  BE/fastapi/quiz-application/docker-compose.yml
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
Labels: 기능 개발

#60 refactor[#59]: 의존성 추가
  BE/fastapi/quiz-application/.gitignore
  BE/fastapi/quiz-application/requirements.txt
Labels: 리팩토링

#61 feat[#56]: 정답페이지 구현, 일부 기능 미적용, api테스트는 DB생성 후 추후 예정
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/Modal/answerExit.tsx
  FE/pdf_quiz/src/Modal/answerSave.tsx
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/MyPage copy.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
Labels: 기능 개발

#67 feat[#64]: 로그아웃
  BE/spring/quiz-application/build.gradle
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/TokenProvider.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/MemberResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ErrorCode.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/PasswordMismatchException.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/MemberServiceImpl.java
Labels: 기능 개발, 리팩토링

#69 refactor[#68] : 불필요 css 코드 제거
  FE/pdf_quiz/src/App.css
Labels: 리팩토링

#72 feat[#70]: PDF 업로드 구현
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/pdf/PdfUploadController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/pdf/Pdf.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/PdfUploadResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ExceptionHandlerController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/pdf/PdfRepository.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadServiceImpl.java
Labels: 기능 개발

#74 Feature/#71 fe pdf 업로드 모달
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/assets/DragFile.png
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
Labels: 기능 개발

#75 feat[#73]: kafka 설정
  BE/spring/quiz-application/build.gradle
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/kafka/KafkaConsumer.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/kafka/KafkaConsumerConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/quiz/Quiz.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/quiz/QuizRepository.java
Labels: 기능 개발

#81 feat[#79] SSE 설정
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/kafka/KafkaConsumer.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/notification/NotificationController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/pdf/PdfUploadController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/pdf/Pdf.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/quiz/Quiz.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/PythonQuizRequest.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/QuizGenerateRequest.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/quiz/QuizOption.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/quiz/QuizResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/EmitterRepository.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/notification/NotificationService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadServiceImpl.java
Labels: 기능 개발

#84 refactor[#80]: 퀴즈 생성 반환값 추가
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/shema/quiz_request.py
Labels: 리팩토링

#87 docs[#85]: document 및 readmd.md 수정
  .github/PULL_REQUEST_TEMPLATE.md
  Document/ERD.png
  Document/전체흐름도.png
  README.md
Labels: 문서

#86 Feature/#82 fe sse 설정
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/Hooks/useSSE.tsx
  FE/pdf_quiz/src/pages/SSEPage.tsx
Labels: 기능 개발

#90 feat[#84] SSE & Kafka 설정
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/kafka/KafkaConsumer.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/notification/NotificationController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/pdf/Pdf.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/quiz/Quiz.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/PythonQuizRequest.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/QuizGenerateRequest.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/pdf/PdfRepository.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/notification/NotificationService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/pdf/PdfUploadServiceImpl.java
Labels: 리팩토링

#92 Feature/#89 fe sse 헤더설정
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/Hooks/useSSE.tsx
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
  FE/pdf_quiz/src/pages/SSEPage.tsx
Labels: 기능 개발

#93 feat[#88]: 퀴즈 페이지 반응형 적용
  FE/pdf_quiz/src/Hooks/OMR.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
Labels: 기능 개발

#101 feat[#100]: 스웨거 인증 제외
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
Labels: 리팩토링

#104 Feature/#97 페이지네이션
  FE/pdf_quiz/src/App.css
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 기능 개발

#106 feat[#103] : 회원가입 api 테스트 완료
  FE/pdf_quiz/package-lock.json
  FE/pdf_quiz/package.json
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
Labels: 기능 개발

#108 feat[#107]: 로그인 방식 변경
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomAuthenticationFilter.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/CustomUserDetailsService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/LoginRequestDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/MemberRepository.java
Labels: 리팩토링

#109 Feature/#105 아이디 찾기 기능 완성
  FE/pdf_quiz/src/Modal/findID.tsx
  FE/pdf_quiz/src/pages/FindAccount.tsx
Labels: 기능 개발

#112 feat[#111]: 인증/인가 헤더 설정
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
Labels: 리팩토링

#114 Feature/#78 fe 마이페이지 기능적용
  FE/pdf_quiz/package-lock.json
  FE/pdf_quiz/package.json
  FE/pdf_quiz/src/Hooks/useDropdown.tsx
  FE/pdf_quiz/src/Modal/folderModal.tsx
  FE/pdf_quiz/src/api/ApiClient.tsx
  FE/pdf_quiz/src/api/ApiFolder.tsx
  FE/pdf_quiz/src/api/ApiQuiz.tsx
  FE/pdf_quiz/src/api/ApiUser.tsx
  FE/pdf_quiz/src/assets/folder2.png
  FE/pdf_quiz/src/components/folderList.tsx
  FE/pdf_quiz/src/components/folderTest.tsx
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/MyPageTest.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
  FE/pdf_quiz/src/pages/answerTest.tsx
  FE/pdf_quiz/tsconfig.app.json
Labels: 기능 개발

#115 feat[#113]: 로그인 요청데이터 변경 및 액세스 토큰 저장 확인 테스트
  FE/pdf_quiz/src/pages/Login.tsx
Labels: 기능 개발

#118 feat[#116]: 유저정보 수정
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/Member.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/EditUserInfoDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java
Labels: 기능 개발

#121 feat[#119]: 회원가입 -> 로그인 -> 로그아웃 모두 api테스트 완료
  FE/pdf_quiz/index.html
  FE/pdf_quiz/src/api/ApiClient.tsx
  FE/pdf_quiz/src/api/ApiFolder.tsx
  FE/pdf_quiz/src/api/ApiQuiz.tsx
  FE/pdf_quiz/src/api/ApiUser.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
  FE/pdf_quiz/vite.config.ts
  package-lock.json
Labels: 기능 개발

#123 Feature/#110 입력값 상태관리
  FE/pdf_quiz/src/Hooks/useSSE.tsx
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 기능 개발

#127 feat[#122]: 내정보 페이지 구현 및 API테스트 완료, Login실패 처리
  FE/pdf_quiz/package-lock.json
  FE/pdf_quiz/package.json
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/api/ApiClient.tsx
  FE/pdf_quiz/src/api/ApiUser.tsx
  FE/pdf_quiz/src/pages/InfoPage.tsx
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
Labels: 기능 개발

#130 refactoring[#94] : 클로드 적용 - 다시해야함
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
Labels: 리팩토링

#131 Feature/#128 퀴즈 불러오기
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
  FE/pdf_quiz/vite.config.ts
Labels: 기능 개발

#134 Feature/#132 퀴즈 불러오기
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 기능 개발

#136 feat[#133] exam관련 API 작성
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/kafka/KafkaConsumer.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/exam/ExamController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/EditUserInfoDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/FolderResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/exam/ExamResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/exam/ExamRepository.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/exam/ExamService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/exam/ExamServiceImpl.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/notification/NotificationService.java
  BE/spring/quiz-application/src/main/resources/data.sql
Labels: 기능 개발, 리팩토링
