Repository August-ToyProject/PDF-Quiz, pull requests merged in 2024-09, with the labels that each got.

#139 Feature/#138 be fast api lang
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
Labels: 리팩토링

#141 feat[#129]: 폴더 관련 API적용 및 관련 코드별로 분리
  FE/pdf_quiz/src/Modal/folderModal.tsx
  FE/pdf_quiz/src/api/ApiClient.tsx
  FE/pdf_quiz/src/api/ApiFolder.tsx
  FE/pdf_quiz/src/api/ApiQuiz.tsx
  FE/pdf_quiz/src/api/ApiUser.tsx
  FE/pdf_quiz/src/assets/reset.png
  FE/pdf_quiz/src/components/folderList.tsx
  FE/pdf_quiz/src/components/folderTest.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/MyPageTest.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
Labels: 리팩토링

#147 Feature/#135 사용자값 상태관리
  FE/pdf_quiz/.gitignore
  FE/pdf_quiz/src/Hooks/OMR.tsx
  FE/pdf_quiz/src/Hooks/Timer.tsx
  FE/pdf_quiz/src/context/QuizContext.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
Labels: 기능 개발

#150 Feature/#144 정답값 전달
  FE/pdf_quiz/src/Hooks/OMR.tsx
  FE/pdf_quiz/src/Hooks/userAnswers.ts
  FE/pdf_quiz/src/Modal/Submit.tsx
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 기능 개발

#152 fix[#151] : npm build 에러 수정
  FE/pdf_quiz/src/Hooks/useSSE.tsx
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/api/ApiQuiz.tsx
  FE/pdf_quiz/src/components/PostIt.tsx
  FE/pdf_quiz/src/event-source-polyfill.d.ts
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/InfoPage.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 버그

#156 refactor: 미사용 변수 및 코드 제거
  FE/pdf_quiz/src/Hooks/useSSE.tsx
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/components/PostIt.tsx
  FE/pdf_quiz/src/pages/InfoPage.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 버그

#158 Design/#155 디자인
  FE/pdf_quiz/index.html
  FE/pdf_quiz/package-lock.json
  FE/pdf_quiz/package.json
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/assets/Logo.svg
  FE/pdf_quiz/src/assets/ServiceLogo.png
  FE/pdf_quiz/src/components/folderList.tsx
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
  FE/pdf_quiz/tailwind.config.js
Labels: 기능 개발

#163 feat: 로딩 스피너 추가
  FE/pdf_quiz/src/Modal/Upload.tsx
Labels: 기능 개발

#165 feature/[#164]: 정답페이지 구현 및 통신
  FE/pdf_quiz/package-lock.json
  FE/pdf_quiz/package.json
  FE/pdf_quiz/src/Hooks/userAnswers.ts
  FE/pdf_quiz/src/Modal/answerSave.tsx
  FE/pdf_quiz/src/api/ApiQuiz.tsx
  FE/pdf_quiz/src/context/QuizContext.tsx
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/MyPageTest.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
  FE/pdf_quiz/src/pages/answerTest.tsx
Labels: 기능 개발

#167 Fix/#159 다크모드 해결
  FE/pdf_quiz/src/assets/Logo_blue.svg
  FE/pdf_quiz/src/index.css
  FE/pdf_quiz/src/pages/InfoPage.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
Labels: 버그

#169 feat[#166]: 개인정보수집동의추가
  FE/pdf_quiz/src/Modal/agreementModal.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
Labels: 기능 개발

#173 Feat/#172 시험지이름커스텀
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/Modal/answerSave.tsx
  FE/pdf_quiz/src/context/QuizContext.tsx
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
Labels: 기능 개발

#175 Design/#174 폰트수정
  FE/pdf_quiz/index.html
  FE/pdf_quiz/src/assets/QuizIcon.svg
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 기능 개발

#178 Feature/#162 be fast api difficult
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
Labels: 리팩토링

#181 Feat/#177 빈답안처리
  FE/pdf_quiz/src/Hooks/userAnswers.ts
  FE/pdf_quiz/src/context/QuizContext.tsx
Labels: 기능 개발

#182 refactor[#162] : 프롬프트 2차 수정
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
Labels: 버그, 리팩토링

#186 design: 퀴즈 페이지 디자인 수정
  FE/pdf_quiz/src/Hooks/OMR.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
Labels: 기능 개발

#188 feat: 로고에 마이페이지 네비게이션 추가
  FE/pdf_quiz/src/pages/InfoPage.tsx
Labels: 기능 개발

#190 feature[#170]: 시험결과확인API통신완료
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/api/ApiQuiz.tsx
  FE/pdf_quiz/src/components/folderList.tsx
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/ListAnswer.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
Labels: 기능 개발

#192 Fix/#189 omr상태관리 수정
  FE/pdf_quiz/src/Hooks/OMR.tsx
  FE/pdf_quiz/src/Hooks/userAnswers.ts
  FE/pdf_quiz/src/Modal/Submit.tsx
  FE/pdf_quiz/src/context/QuizContext.tsx
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/Quiz.tsx
Labels: 버그

#193 feat[#191]: PDF Upload버튼 반응형 시 적용, 버튼 커서 숨김
  FE/pdf_quiz/src/components/folderList.tsx
  FE/pdf_quiz/src/pages/ListAnswer.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
Labels: 리팩토링

#197 refactor[#196] : 프롬프트 수정(협박 메시지 추가)
  BE/fastapi/quiz-application/src/app/api/quiz_service/helpers/quiz_service.py
  BE/fastapi/quiz-application/src/app/api/quiz_service/service/quiz_service.py
Labels: 리팩토링

#198 feat[#180] 시간처리 리팩터링
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/exam/ExamResultRequest.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/notification/NotificationService.java
Labels: 리팩토링

#202 refacor[#201] : http -> https
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 리팩토링

#204 feat: 비활성화 인풋데이터 접근 시 업로드 표시, 정답페이지 시간 이미지 수정
  FE/pdf_quiz/index.html
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/components/folderTest.tsx
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/tailwind.config.js
Labels: 기능 개발

#205 feat[#199] be async
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/QuizApplication.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/async/AsyncConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/async/AsyncService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/jwt/JwtFilter.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/kafka/KafkaConsumer.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/kafka/KafkaConsumerConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/notification/NotificationController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/domain/quiz/Quiz.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/quiz/QuizResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/repository/EmitterRepository.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/notification/EmitterService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/notification/NotificationService.java
Labels: 리팩토링

#208 feat[#206] docker파일 작성
  BE/spring/quiz-application/Dockerfile
Labels: 기능 개발

#212 Fix/#210 타이머 타이밍수정(사용자 피드백)
  .github/workflows/react_git_action.yaml
  FE/pdf_quiz/src/Hooks/Timer.tsx
  FE/pdf_quiz/src/context/QuizContext.tsx
  FE/pdf_quiz/src/pages/QuizData.tsx
Labels: 버그

#214 feat[#206]: 도커
  BE/spring/quiz-application/build.gradle
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/security/SecurityConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/common/ErrorCode.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/DuplicateEmailException.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/MemberErrorCode.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/exception/member/MemberException.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java
Labels: 기능 개발

#220 feat[#216]: MyPage이미지구현
  FE/pdf_quiz/index.html
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/Modal/actionModal.tsx
  FE/pdf_quiz/src/assets/Star_gray.png
  FE/pdf_quiz/src/assets/Star_yellow.png
  FE/pdf_quiz/src/assets/bottom_text.png
  FE/pdf_quiz/src/assets/center_image.png
  FE/pdf_quiz/src/assets/top_text.png
  FE/pdf_quiz/src/components/footer.tsx
  FE/pdf_quiz/src/pages/TempPage.tsx
Labels: 리팩토링

#222 Feat/#213 메인페이지
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/assets/Logo_blue.svg
  FE/pdf_quiz/src/assets/MainIcon.svg
  FE/pdf_quiz/src/components/Header.tsx
  FE/pdf_quiz/src/context/LoginContext.tsx
  FE/pdf_quiz/src/pages/MainPage.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
  FE/pdf_quiz/src/pages/TempPage.tsx
Labels: 기능 개발

#224 Feat/#223 로그인모바일
  FE/pdf_quiz/src/assets/Logo.svg
  FE/pdf_quiz/src/pages/FindAccount.tsx
  FE/pdf_quiz/src/pages/Login.tsx
Labels: 기능 개발

#225 feature/업로드 이미지 수정 및 에러메세지 추가
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/TempPage.tsx
  FE/pdf_quiz/tailwind.config.js
Labels: 기능 개발, 리팩토링

#228 feature/마이페이지좌측디테일수정
  FE/pdf_quiz/src/pages/TempPage.tsx
Labels: 리팩토링

#229 feat: 구글 소셜 로그인 추가
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/assets/Google.png
  FE/pdf_quiz/src/pages/GoogleRedirect.tsx
  FE/pdf_quiz/src/pages/Login.tsx
Labels: 기능 개발

#231 Upload모달모션추가
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/TempPage.tsx
Labels: 리팩토링

#232 Feat/#226 help
  FE/pdf_quiz/src/App.tsx
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/api/ApiUser.tsx
  FE/pdf_quiz/src/assets/Google.png
  FE/pdf_quiz/src/components/Header.tsx
  FE/pdf_quiz/src/pages/Answer.tsx
  FE/pdf_quiz/src/pages/GoogleRedirect.tsx
  FE/pdf_quiz/src/pages/ListAnswer.tsx
  FE/pdf_quiz/src/pages/Login.tsx
  FE/pdf_quiz/src/pages/SignUp.tsx
  FE/pdf_quiz/src/pages/TempPage.tsx
Labels: 기능 개발
