Repository August-ToyProject/PDF-Quiz, pull requests merged in 2024-10, with the labels that each got.

#234 fix/폴더 좌측 정렬 수정
  FE/pdf_quiz/src/Modal/Upload.tsx
  FE/pdf_quiz/src/pages/TempPage.tsx
Labels: 리팩토링

#235 Feature/#227 be 오답노트
  BE/spring/quiz-application/build.gradle
  BE/spring/quiz-application/http/member.http
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/mail/MailConfig.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/config/mail/MailService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/controller/MemberController.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/request/SignupDto.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/dto/response/EmailVerificationResponse.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberService.java
  BE/spring/quiz-application/src/main/java/com/quizapplication/service/member/MemberServiceImpl.java
  BE/spring/quiz-application/src/test/java/com/quizapplication/member/MemberServiceTest.java
Labels: 기능 개발

#237 feature/이메일인증확인 및 마이페이지 디자인 수정
  FE/pdf_quiz/index.html
  FE/pdf_quiz/src/api/ApiUser.tsx
  FE/pdf_quiz/src/assets/profileImage.png
  FE/pdf_quiz/src/components/Header.tsx
  FE/pdf_quiz/src/index.css
  FE/pdf_quiz/src/pages/SignUp.tsx
  FE/pdf_quiz/src/pages/TempPage.tsx
  FE/pdf_quiz/tailwind.config.js
Labels: 기능 개발, 리팩토링

#241 feature/이메일인증디버깅 및 폰트 수정
  FE/pdf_quiz/src/Modal/actionModal.tsx
  FE/pdf_quiz/src/pages/MyPage.tsx
  FE/pdf_quiz/src/pages/TempPage.tsx
Labels: 버그, 리팩토링

#242 feature/마이페이지UI수정
  .vscode/settings.json
  FE/pdf_quiz/src/pages/MyPage.tsx
Labels: 리팩토링
